#!/bin/zsh
# Scans images/, converts any non-jpg to jpg, renames every photo in a folder to
# clean sequential names (1.jpg, 2.jpg, ...), and writes photos.js — the manifest
# the page reads to build each stop's carousel. Clean names avoid spaces/parens breaking things.
ROOT="$(cd "$(dirname "$0")" && pwd)"
IMG="$ROOT/images"
OUT="$ROOT/photos.js"

# 1) convert dropped HEIC/PNG/WEBP/AVIF/JPEG to .jpg (keep every photo)
find "$IMG" -mindepth 2 -type f \( -iname '*.heic' -o -iname '*.png' -o -iname '*.webp' -o -iname '*.avif' -o -iname '*.jpeg' \) | while read -r f; do
  base="${f%.*}"
  if sips -s format jpeg "$f" --out "$base.jpg" >/dev/null 2>&1; then rm -f "$f"; fi
done

# 2) renumber each folder's jpgs to 1.jpg..N.jpg (two-pass via temp names to avoid collisions)
find "$IMG" -mindepth 2 -type d | while read -r d; do
  i=0
  find "$d" -maxdepth 1 -type f -iname '*.jpg' | LC_ALL=C sort | while read -r f; do
    i=$((i+1)); mv -f "$f" "$(printf '%s/__t%03d.jpg' "$d" "$i")"
  done
  i=0
  find "$d" -maxdepth 1 -type f -name '__t*.jpg' | LC_ALL=C sort | while read -r f; do
    i=$((i+1)); mv -f "$f" "$d/$i.jpg"
  done
done

# 3) write the manifest as a JS global (works over file:// and https, no fetch/CORS)
{
  echo "// AUTO-GENERATED by publish-photos.command — do not edit by hand."
  echo "window.PHOTOS = {"
  for tour in honey-traditions native-kitchen city-tour-sky-show; do
    echo "  \"$tour\": {"
    for d in "$IMG/$tour"/*/; do
      [ -d "$d" ] || continue
      folder=$(basename "$d")
      imgs=$(find "$d" -maxdepth 1 -type f -iname '*.jpg' -exec basename {} \; | sort -n | sed 's/.*/"&"/' | paste -sd, -)
      echo "    \"$folder\": [$imgs],"
    done
    echo "  },"
  done
  echo "};"
} > "$OUT"
echo "Wrote $OUT"
