// AUTO-GENERATED by publish-photos.command — do not edit by hand.
window.PHOTOS = {
  "honey-traditions": {
    "beeswax-candle-marketplace": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg"],
    "ceremonial-cacao": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg","10.jpg","11.jpg","12.jpg","13.jpg"],
    "hero": ["1.jpg"],
    "jungle-liqueur-tasting": [],
    "melipona-honey-tasting": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg"],
    "tierra-maya-jungle-sanctuary": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg","10.jpg","11.jpg","12.jpg","13.jpg"],
    "zikil-paak-tortillas": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg","10.jpg","11.jpg","12.jpg","13.jpg","14.jpg","15.jpg"],
  },
  "native-kitchen": {
    "cook-it-yourself": [],
    "cross-the-island": [],
    "hero": [],
    "jungle-to-table-lunch": [],
    "scenic-start": [],
    "shop-the-market": [],
    "street-tortilleria": [],
  },
  "city-tour-sky-show": {
    "corpus-christi-church": ["1.jpg","2.jpg","3.jpg"],
    "hero": ["1.jpg"],
    "malecon-aztec-eagles": ["1.jpg","2.jpg","3.jpg","4.jpg"],
    "mayan-sky-show": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg"],
    "mercado-municipal": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg"],
    "mestizaje-monument": ["1.jpg","2.jpg","3.jpg"],
    "plaza-central": ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg"],
  },
};
